before_script:
  - mkdir -p tmp/{pids,cache} log
  - bundle check || bundle install
# workaround for plugins with Gemfile
  - perl -pi -e 's/--local //' script/noosfero-plugins
  - script/noosfero-plugins disableall
  - bundle exec rake makemo &>/dev/null
# database
  - cp config/database.yml.gitlab-ci config/database.yml
  - createdb gitlab_ci_test || true
  - bundle exec rake db:schema:load &>/dev/null
  - bundle exec rake db:migrate &>/dev/null

units:
  script: bundle exec rake test:units
functionals:
  script: bundle exec rake test:functionals
integration:
  script: bundle exec rake test:integration
cucumber:
  script: bundle exec rake cucumber
selenium:
  script: bundle exec rake selenium
plugins:
  script: bundle exec rake test:noosfero_plugins

