image: noosfero/ci

before_script:
  - mkdir -p locale # makes quick-start skip compiling translations
  - ./script/silent-quick-start

units:
  script: bundle exec rake test:units
functionals:
  script: bundle exec rake test:functionals
integration:
  script: bundle exec rake test:integration
cucumber:
  script: bundle exec rake cucumber
selenium:
  script: bundle exec rake selenium
plugins:
  script: bundle exec rake test:noosfero_plugins

