language: ruby
rvm:
# for 2.2 support we need to upgrade the pg gem
  - 2.1.6
cache: bundler

sudo: false
addons:
  apt:
    packages:
      - po4a
      - iso-codes
      - tango-icon-theme
      - pidgin-data
      # for gem extensions
      - libmagickwand-dev
      - libpq-dev
      - libreadline-dev
      - libsqlite3-dev
      - libxslt1-dev

before_script:
  - mkdir -p tmp/pids log
  - bundle check || bundle install
  - script/noosfero-plugins disableall
  - bundle exec rake makemo &>/dev/null
# database
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database myapp_test;' -U postgres
  - bundle exec rake db:schema:load &>/dev/null
  - bundle exec rake db:migrate &>/dev/null

env:
  - TASK=test:units
  - TASK=test:functionals
  - TASK=test:integration
  - TASK=cucumber
  - TASK=selenium
  - TASK=test:noosfero_plugins

script:
  - bundle exec rake $TASK

